[package]
name = "range-search"
version = "0.1.0"
edition = "2024"

[dependencies]
num-integer = { version = "0.1.46", default-features = false }
num-traits = { version = "0.2.19", default-features = false }

[dev-dependencies]
num-bigint = "0.4.6"
